use super::Strategem;

mod defensive;
mod mission;
mod offensive;
mod supply;

pub const ALL_STRATEGEMS: [Strategem; 63] = [
    supply::lift850_jump_pack(),
    supply::b1_supply_pack(),
    supply::axlas5_guard_dog_rover(),
    supply::sh20_ballistic_shield_backpack(),
    supply::sh32_shield_generator_pack(),
    supply::axar23_guard_dog(),
    supply::mg43_machine_gun(),
    supply::apw1_antimateriel_rifle(),
    supply::m105_stalwart(),
    supply::eat17_expendable_antitank(),
    supply::gr8_recoilless_rifle(),
    supply::flam40_flamethrower(),
    supply::ac8_autocannon(),
    supply::mg206_heavy_machine_gun(),
    supply::rs422_railgun(),
    supply::faf14_spear_launcher(),
    supply::gl21_grenade_launcher(),
    supply::las98_laser_cannon(),
    supply::arc3_arc_thrower(),
    supply::las99_quasar_cannon(),
    supply::rl77_airburst_rocket_launcher(),
    supply::exo45_patriot_exosuit(),
    supply::exo45_emancipator_exosuit(),
    mission::reinforce(),
    mission::sos_beacon(),
    mission::resupply(),
    mission::nux223_hellbomb(),
    mission::sssd_delivery(),
    mission::seismic_probe(),
    mission::upload_data(),
    mission::eagle_rearm(),
    mission::illumination_flare(),
    mission::seaf_artillery(),
    mission::super_earth_flag(),
    defensive::emg101_hmg_emplacement(),
    defensive::fx12_shield_generator_relay(),
    defensive::aarc3_tesla_tower(),
    defensive::md6_anti_personnel_minefield(),
    defensive::mdi4_incendiary_mines(),
    defensive::amg43_machine_gun_sentry(),
    defensive::ag16_galting_sentry(),
    defensive::am12_mortar_sentry(),
    defensive::aac8_autocannon_sentry(),
    defensive::amls4x_rocket_sentry(),
    defensive::am23_ems_mortar_sentry(),
    offensive::orbital_gatling_barrage(),
    offensive::orbital_airburst_strike(),
    offensive::orbital_120mm_he_barrage(),
    offensive::orbital_380mm_he_barrage(),
    offensive::orbital_walking_barrage(),
    offensive::orbital_laser(),
    offensive::orbital_railcannon_strike(),
    offensive::orbital_precision_strike(),
    offensive::orbital_gas_strike(),
    offensive::orbital_ems_strike(),
    offensive::orbital_smoke_strike(),
    offensive::eagle_strafing_run(),
    offensive::eagle_air_strike(),
    offensive::eagle_cluster_bomb(),
    offensive::eagle_napalm_airstrike(),
    offensive::eagle_smoke_strike(),
    offensive::eagle_110mm_rocket_pods(),
    offensive::eagle_500kg_bomb(),
];
